### ISSUE TITLE
render combine Arbic and English

### ISSUE THREAD

**Issue by armanhossiny** [DelinWorks/arabic-text-renderer-cpp-axmol#2]
Hi Mohammed
always English first line, I want use two way combine:

![8](https://github.com/DelinWorks/arabic-text-renderer-cpp-axmol/assets/42970068/d3bec12d-94f1-4583-9140-49ad3611dead)

but always render:
![9](https://github.com/DelinWorks/arabic-text-renderer-cpp-axmol/assets/42970068/0f31a5b3-a684-4339-9a6e-727a91c1e4a7)

text:
سلام world
World سلام         

you can test two way?

**Comment by DelinWorks** [comment]
I get the same result as Visual Studio text renderer I don't know how to regenerate the issue

![image](https://github.com/DelinWorks/arabic-text-renderer-cpp-axmol/assets/45469625/510e43f2-7f71-466b-aae5-2143bcac5608)
![image](https://github.com/DelinWorks/arabic-text-renderer-cpp-axmol/assets/45469625/8573a8d5-d909-469f-9728-24f0c1cff1a9)

And the other order:

![image](https://github.com/DelinWorks/arabic-text-renderer-cpp-axmol/assets/45469625/5e1998a9-2d36-46c8-b709-ee54389185cc)
![image](https://github.com/DelinWorks/arabic-text-renderer-cpp-axmol/assets/45469625/6eb51164-f79e-434f-b89f-6ba74f3984e7)

**Comment by DelinWorks** [comment]
@armanhossiny I assume you figured it out but if you didn't then just reopen the issue
